#version: '3.8'
#
#services:
#  mysql:
#    image: mysql:latest
#    restart: unless-stopped
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: 'db'
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password
#    ports:
#      - "3308:3306"
#
#  spring-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - mysql
#    ports:
#      - "5556:5555"  # Updated port mapping
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/spring_generic  # Updated port in the URL
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: f1s0ft@123
#    networks:
#      - backend
#
#networks:
#  backend:
#    driver: bridge
